### ISSUE TITLE
about on fire alert console

### ISSUE THREAD

**Issue by skymon4** [polivilas/EmuTarkov#13]
Sometimes a console appears when my gun is self-firing and I'm fighting AI.

**Comment by swagmoneyinc** [comment]
Having the same/similar issue. Seems to be caused by killing the same AI scav that I think is first in the list of bot_generate.json. I attached a screenshot of the error. Also if you're playing with easy AI selected you'll run into this issue far more often than using random. 
![Untitled](https://user-images.githubusercontent.com/50127921/56939512-d7592500-6ad6-11e9-9f70-1f751ecb91e3.png)

**Comment by skymon4** [comment]
but I can not solve it，I think it`s my wrong about config. and then when I deployment of firearms,I can not save it

**Comment by swagmoneyinc** [comment]
seems like the issue occurs when the same AI is generated multiple times and then one of them is killed. I can look more into it after this week.

**Comment by swagmoneyinc** [comment]
the problem is fixed in BALIST0N's version.

**Comment by ghost** [comment]
its about bots, in this version bots are all the same so when you kill a duplicated bot the game throw an error, also when your profile have developer mode enabled, the console pop up every time when an error occurs

**Comment by InNoHurryToCode** [comment]
Thanks to merge #12 this issue is resolved. @polivilas you might wanna close this.
